[package]
name = "helloasso"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0"
envir = "1.0"
attohttpc = "0.29"
scraper = "0.23"
serde_json = "1.0"
regex = "1.8"
thiserror = "2.0"
log = "0.4"
