[package]
name = "helloasso"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
envir = "0.3"
attohttpc = "0.28"
scraper = "0.19"
serde_json = "1.0"
regex = "1.8"
thiserror = "1.0"
log = "0.4"
