[package]
name = "helloasso"
version = "0.1.0"
edition = "2021"

[dependencies]
envir = "0.3"
attohttpc = "0.26"
scraper = "0.18"
serde_json = "1.0.96"
regex = "1.8.1"
thiserror = "1.0.40"
log = "0.4.17"

[dependencies.actix-web]
version = "4.0"
